language: php

php:
  - 7.0
  - hhvm-nightly
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: nightly
  fast_finish: true

script: phpunit
